FUNCTION f(x)  RESULT(r)    !DEFINO AQUI A FUNTÇÃO DESEJADA, PARA QUE SEJA MAIS FÁCIL CHAMÁ-LA
   REAL*8   :: x, r
   r = (exp(2*x))*COS(x/4)
END FUNCTION

FUNCTION der(x)   RESULT(r)   !DERIVO A FUNÇÃO MANUALMENTE, PARA PODER DETERMINAR O ERRO DA DERIVADA "VERDADEIRA" EM RELAÇÃO À ENCONTRADA COMPUTACIONALMENTE
   REAL*8   :: x, r
   R = -(SIN(x/4) - 8*COS(x/4))*EXP(2*x)/4
END FUNCTION

PROGRAM ex1
   IMPLICIT NONE
   REAL*8   :: f, x, der
   REAL*8   :: ff, f3s, f5s
   REAL*8  :: h
   INTEGER  :: i    !DEFINIÇÃO DAS VARIÁVEIS A SEREM USADAS

   x = 1    !O VALOR PEDIDO DE X É 1
   DO i = 1, 100000   !UMA VEZ QUE A COMPLEXIDADE DO PROGRAMA SEGUE LINEARMENTE COM i, POSSO UTILIZAR UM GRANDE No DE PONTOS (10**5 NO CASO)
      h = FLOAT(i)/100000   !DEFINDO H DESTA FORMA, ELE VARIA DE 1/10**5 ATÉ 1
      ff = (f(x+h) - f(x))/h - der(x)   !CALCULO O ERRO DE FF
      f3s = (f(x+h) - f(x-h))/(2*h) - der(x)    !CALCULO O ERRO DE F3S
      f5s  =  (-f(x + 2*h) + 8*f(x + h) - 8*f(x - h) + f(x - 2*h))/(12*h) - der(x)    !CALCULO O ERRO DE F5S
      WRITE(1,*)LOG10(h),',', LOG10(ABS(ff)),',',LOG10(ABS(f3s)),',', LOG10(ABS(f5s))   !ESCREVO O LOG DOS RESULTADOS NUM ARQUIVO PARA SER PLOTADO POR LOG(H)
   ENDDO

END PROGRAM
